require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe BilansController do

  def mock_bilan(stubs={})
    @mock_bilan ||= mock_model(Bilan, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all bilans as @bilans" do
      Bilan.stub(:all) { [mock_bilan] }
      get :index
      assigns(:bilans).should eq([mock_bilan])
    end
  end

  describe "GET show" do
    it "assigns the requested bilan as @bilan" do
      Bilan.stub(:find).with("37") { mock_bilan }
      get :show, :id => "37"
      assigns(:bilan).should be(mock_bilan)
    end
  end

  describe "GET new" do
    it "assigns a new bilan as @bilan" do
      Bilan.stub(:new) { mock_bilan }
      get :new
      assigns(:bilan).should be(mock_bilan)
    end
  end

  describe "GET edit" do
    it "assigns the requested bilan as @bilan" do
      Bilan.stub(:find).with("37") { mock_bilan }
      get :edit, :id => "37"
      assigns(:bilan).should be(mock_bilan)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created bilan as @bilan" do
        Bilan.stub(:new).with({'these' => 'params'}) { mock_bilan(:save => true) }
        post :create, :bilan => {'these' => 'params'}
        assigns(:bilan).should be(mock_bilan)
      end

      it "redirects to the created bilan" do
        Bilan.stub(:new) { mock_bilan(:save => true) }
        post :create, :bilan => {}
        response.should redirect_to(bilan_url(mock_bilan))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved bilan as @bilan" do
        Bilan.stub(:new).with({'these' => 'params'}) { mock_bilan(:save => false) }
        post :create, :bilan => {'these' => 'params'}
        assigns(:bilan).should be(mock_bilan)
      end

      it "re-renders the 'new' template" do
        Bilan.stub(:new) { mock_bilan(:save => false) }
        post :create, :bilan => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested bilan" do
        Bilan.stub(:find).with("37") { mock_bilan }
        mock_bilan.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :bilan => {'these' => 'params'}
      end

      it "assigns the requested bilan as @bilan" do
        Bilan.stub(:find) { mock_bilan(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:bilan).should be(mock_bilan)
      end

      it "redirects to the bilan" do
        Bilan.stub(:find) { mock_bilan(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(bilan_url(mock_bilan))
      end
    end

    describe "with invalid params" do
      it "assigns the bilan as @bilan" do
        Bilan.stub(:find) { mock_bilan(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:bilan).should be(mock_bilan)
      end

      it "re-renders the 'edit' template" do
        Bilan.stub(:find) { mock_bilan(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested bilan" do
      Bilan.stub(:find).with("37") { mock_bilan }
      mock_bilan.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the bilans list" do
      Bilan.stub(:find) { mock_bilan }
      delete :destroy, :id => "1"
      response.should redirect_to(bilans_url)
    end
  end

end
