require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe VillesController do

  def mock_ville(stubs={})
    @mock_ville ||= mock_model(Ville, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all villes as @villes" do
      Ville.stub(:all) { [mock_ville] }
      get :index
      assigns(:villes).should eq([mock_ville])
    end
  end

  describe "GET show" do
    it "assigns the requested ville as @ville" do
      Ville.stub(:find).with("37") { mock_ville }
      get :show, :id => "37"
      assigns(:ville).should be(mock_ville)
    end
  end

  describe "GET new" do
    it "assigns a new ville as @ville" do
      Ville.stub(:new) { mock_ville }
      get :new
      assigns(:ville).should be(mock_ville)
    end
  end

  describe "GET edit" do
    it "assigns the requested ville as @ville" do
      Ville.stub(:find).with("37") { mock_ville }
      get :edit, :id => "37"
      assigns(:ville).should be(mock_ville)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created ville as @ville" do
        Ville.stub(:new).with({'these' => 'params'}) { mock_ville(:save => true) }
        post :create, :ville => {'these' => 'params'}
        assigns(:ville).should be(mock_ville)
      end

      it "redirects to the created ville" do
        Ville.stub(:new) { mock_ville(:save => true) }
        post :create, :ville => {}
        response.should redirect_to(ville_url(mock_ville))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved ville as @ville" do
        Ville.stub(:new).with({'these' => 'params'}) { mock_ville(:save => false) }
        post :create, :ville => {'these' => 'params'}
        assigns(:ville).should be(mock_ville)
      end

      it "re-renders the 'new' template" do
        Ville.stub(:new) { mock_ville(:save => false) }
        post :create, :ville => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested ville" do
        Ville.stub(:find).with("37") { mock_ville }
        mock_ville.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :ville => {'these' => 'params'}
      end

      it "assigns the requested ville as @ville" do
        Ville.stub(:find) { mock_ville(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:ville).should be(mock_ville)
      end

      it "redirects to the ville" do
        Ville.stub(:find) { mock_ville(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(ville_url(mock_ville))
      end
    end

    describe "with invalid params" do
      it "assigns the ville as @ville" do
        Ville.stub(:find) { mock_ville(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:ville).should be(mock_ville)
      end

      it "re-renders the 'edit' template" do
        Ville.stub(:find) { mock_ville(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested ville" do
      Ville.stub(:find).with("37") { mock_ville }
      mock_ville.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the villes list" do
      Ville.stub(:find) { mock_ville }
      delete :destroy, :id => "1"
      response.should redirect_to(villes_url)
    end
  end

end
